FROM nginx:latest

WORKDIR /server

COPY ./nginx/nginx_my_nginx.conf /etc/nginx/nginx.conf

COPY 6run.sh .

RUN chown -R nginx:nginx /server && \
    chmod -R 755 /server && \
    touch /var/run/nginx.pid && \
    chown -R nginx:nginx /var/run/nginx.pid && \
    chown -R nginx:nginx /var/cache/nginx && \
    chown -R nginx:nginx /var/log/nginx

USER nginx
ENTRYPOINT [ "./6run.sh" ]
CMD ["nginx", "-g", "daemon off;"]
